extends Node

const ENEMY := "ENEMY"
const LEVEL_MANAGER := "LEVEL_MANAGER"
const LEVEL_MANAGER_SPACE := "LEVEL_MANAGER_SPACE"
const CREDIT := "CREDIT"
const LEVEL_NODE := "LEVEL_NODE"
const PLAYER := "PLAYER"
const CREDIT_PARENT := "CREDIT_PARENT"
const PLAYER_BULLET := "PLAYER_BULLET"
const PLAYER_BULLET_POOL := "PLAYER_BULLET_POOL"
const ENEMY_BULLET_POOL := "ENEMY_BULLET_POOL"
